# Generated by Django 6.0.5 on 2026-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='task_types',
            field=models.ManyToManyField(to='webapp.tasktype', verbose_name='Типы задач'),
        ),
    ]
